version: "3.7"
services:
    app:
        build:
          context: ./docker/php
          dockerfile: Dockerfile
          args:
              - CURRENT_UID=${CURRENT_UID}
        image: drum-n-code-app
        container_name: ${CONTAINER_PREFIX}-app
        restart: unless-stopped
        working_dir: /var/www/
        tty: true
        volumes:
          - ./:/var/www
          - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
          - drum-n-code

    db:
      image: postgis/postgis:15-3.3
      restart: always
      container_name:  ${CONTAINER_PREFIX}-db
      environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      volumes:
        - ./docker/postgres:/var/lib/postgresql/data
      ports:
          - ${DB_CONTAINER_PORT}:${DB_PORT}
      networks:
          - drum-n-code

    nginx:
        image: nginx:1.17-alpine
        container_name:  ${CONTAINER_PREFIX}-nginx
        restart: unless-stopped
        tty: true
        ports:
          - ${NGINX_CONTAINER_PORT}:80
        volumes:
          - ./:/var/www
          - ./docker/nginx:/etc/nginx/conf.d
        networks:
          - drum-n-code

networks:
    drum-n-code:
        driver: bridge
